name: Merge Schedule

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - edited
  schedule:
    - cron: '30 11 * * *' # UTC 11:30 -> 한국 20:30 //test2

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
