name: Merge Schedule

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - edited
  schedule:
    - cron: '30 10 * * *' # UTC 10:30 -> 한국 19:30

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
