name: Merge Schedule

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - edited
  schedule:
    - cron: '20 12 * * *' # UTC 12:20 -> 한국 21:20 //test3

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AUTO_DEPLOY:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/client
            ./deploy.sh
