name: Merge Schedule

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - edited
  schedule:
    - cron: '45 11 * * *' # UTC 11:45 -> 한국 20:45 //test2

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
